CREATE TABLE `company_registry_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`lead_id` text NOT NULL,
	`cnpj` text NOT NULL,
	`legal_name` text NOT NULL,
	`trade_name` text,
	`registration_status` text NOT NULL,
	`primary_cnae` text,
	`secondary_cnaes` text,
	`opened_at` text,
	`size` text,
	`legal_nature` text,
	`address` text,
	`city` text,
	`state` text,
	`postal_code` text,
	`match_confidence` integer NOT NULL,
	`match_source` text NOT NULL,
	`match_evidence` text,
	`registry_source` text NOT NULL,
	`registry_fetched_at` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE no action
);
